
### Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZmxvd2RhdGEuY29tIiwiaWF0IjoxNzU5MTEzNjU0LCJleHAiOjE3NTkxMTcyNTR9.wEqLouIg4qa3TpKQEmNabZZaaY55d9jRlH_4c943Gas

@checkingId = 11
###
GET http://localhost:3333/checkings 
Authorization: Bearer {{token}}

###
GET http://localhost:3333/checkings/{{checkingId}}
Authorization: Bearer {{token}}

###
POST http://localhost:3333/checkings 
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "receiptDate": "2025-09-21T23:45:00.000Z"
}

###
POST http://localhost:3333/checkings/lines 
Authorization: Bearer {{token}}
Content-Type: application/json

[
  {
    "checkingId": {{checkingId}},
    "supplyItemId": 1,
    "receivedQty": 100,
    "unitOfMeasure": "KG" 
  }
]

###
PATCH http://localhost:3333/checkings/{{checkingId}}/lines/9
Authorization: Bearer {{token}}
Content-Type: application/json

{ "receivedQty": 90, "unitOfMeasure": "KG" }

###
DELETE http://localhost:3333/checkings/{{checkingId}}/lines/12
Authorization: Bearer {{token}}
Content-Type: application/json

###
POST http://localhost:3333/checkings/{{checkingId}}/conclude 
Authorization: Bearer {{token}}
Content-Type: application/json

###
DELETE http://localhost:3333/checkings/{{checkingId}} 
Authorization: Bearer {{token}}
