### Variables
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZmxvd2RhdGEuY29tIiwiaWF0IjoxNzU5MTk3OTQyLCJleHAiOjE3NTkyMDE1NDJ9.d_8z78hCnGf7AJrKjx-LHYgX1TFKlfSg82_qCwQDvhE
@checkingId = 1
###

GET http://localhost:3333/inventory 
Authorization: Bearer {{token}}

