### Variables 
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZmxvd2RhdGEuY29tIiwiaWF0IjoxNzU5MTEwMDM3LCJleHAiOjE3NTkxMTM2Mzd9.pWCYdJOKyO1HE9zU-dyQR9-ylXCoUd0ctHuCNxLWNHU

post http://localhost:3333/supply
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Laranja de DoisBigo",
    "code": "321",
    "description": "Faz suco tbm",
    "price": 0.50,
    "supplierId": 1 
}

###

GET http://localhost:3333/supply
Authorization: Bearer {{token}} 


###
get http://localhost:3333/supply/2
Authorization: Bearer {{token}} 

###
GET http://localhost:3333/supply/getByCode/123
Authorization: Bearer {{token}} 

