### Variables 
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZmxvd2RhdGEuY29tIiwiaWF0IjoxNzU4NTAwNzQ0LCJleHAiOjE3NTg1MDQzNDR9.mBjs27fFNcm2t9zEgsXvsWHhSeGreM4PyCe7SnmEeE4

post http://localhost:3333/supply
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Acerrola",
    "code": "123",
    "description": "Acerrola pra fazer suco BEEEEM doce",
    "price": 1.50,
    "supplierId": 1 
}

###

GET http://localhost:3333/supply
Authorization: Bearer {{token}} 


###
get http://localhost:3333/supply/2
Authorization: Bearer {{token}} 