### Variables 
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiYWRtaW5AZmxvd2RhdGEuY29tIiwiaWF0IjoxNzU4NTk2NDcxLCJleHAiOjE3NTg2MDAwNzF9.nKOr8V3duwTYcJCIAnETOYLqfLl3EA-1ozv_avze0zw

post http://localhost:3333/supply
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Laranja de DoisBigo",
    "code": "321",
    "description": "Faz suco tbm",
    "price": 0.50,
    "supplierId": 1 
}

###

GET http://localhost:3333/supply
Authorization: Bearer {{token}} 


###
get http://localhost:3333/supply/2
Authorization: Bearer {{token}} 